<?php

namespace Database\Factories;

use App\Models\User;
use Illuminate\Database\Eloquent\Factories\Factory;
use Illuminate\Support\Str;

class CfdProjectFactory extends Factory
{
    public function definition(): array
    {
        $cfdTitles = [
            'Aerodynamic Drag Optimization of an F1 Front Wing',
            'Thermal Analysis of a Lithium-Ion Battery Pack',
            'NACA 0012 Airfoil Stall Characteristics at High Re',
            'Turbulent Flow Analysis in a 90-Degree Pipe Bend',
            'Wind Tunnel Simulation of a Concept Electric Vehicle',
            'Heat Transfer in a Shell and Tube Heat Exchanger',
            'Ahmed Body Wake Topology and Vortex Structures',
            'Supersonic Flow Over a 2D Wedge',
            'Cavitation Simulation in a Centrifugal Pump',
            'HVAC Airflow Distribution in an Office Environment'
        ];

        $cfdDescriptions = [
            'This project investigates the aerodynamic drag and downforce generated by a multi-element wing using OpenFOAM. The k-omega SST turbulence model is applied to accurately predict flow separation.',
            'A comprehensive thermal management study simulating cooling channels and conjugate heat transfer to maintain optimal operating temperatures.',
            'Validation case for lift and drag coefficients computed across various angles of attack, up to the critical stall angle, comparing Spalart-Allmaras with experimental wind tunnel data.',
            'Study of secondary flow structures, turbulence intensity, and pressure drop across complex geometries using Large Eddy Simulation (LES).',
            'Focuses on external aerodynamics to minimize the drag coefficient (Cd). Mesh refinement zones are placed around the wake region to capture shedding vortices.',
        ];

        $title = $this->faker->randomElement($cfdTitles);

        return [
            'user_id'          => User::factory(),
            'title'            => $title,
            'slug'             => Str::slug($title) . '-' . Str::random(6),
            'description'      => $this->faker->randomElement($cfdDescriptions),
            'software'         => $this->faker->randomElement(['OpenFOAM', 'Ansys Fluent', 'StarCCM+', 'SU2', 'SimScale']),
            'solver'           => $this->faker->randomElement(['simpleFoam', 'pimpleFoam', 'rhoCentralFoam', 'interFoam', 'buoyantBoussinesqSimpleFoam']),
            'mesh_cells'       => $this->faker->numberBetween(500000, 15000000),
            'reynolds_number'  => $this->faker->randomFloat(0, 10000, 5000000),
            'turbulence_model' => $this->faker->randomElement(['k-epsilon (Realizable)', 'k-omega SST', 'LES (Smagorinsky)', 'Spalart-Allmaras', 'Laminar']),
            'simulation_type'  => $this->faker->randomElement([
                'External Aerodynamics', 'Internal Flow',
                'Conjugate Heat Transfer', 'Multiphase Flow', 'Compressible Flow'
            ]),
            'results_summary'  => 'The simulation converged after ' . $this->faker->numberBetween(300, 2000) . ' iterations. Residuals dropped below 1e-4. The predicted drag coefficient aligns with experimental benchmarks with an error margin of less than 3%.',
            'status'           => 'published',
            'views_count'      => $this->faker->numberBetween(15, 1200),
        ];
    }
}